# Generated by Django 5.0.1 on 2024-08-30 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('parent_number', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=None)),
                ('designation', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
