# Generated by Django 5.0.1 on 2024-09-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.AddField(
            model_name='profile',
            name='assignments',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='fees_paid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='fess_pending',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='total_fees',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
