# Generated by Django 5.0.1 on 2024-09-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_studentprofile_fess_pending_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
