# Generated by Django 5.0.1 on 2024-09-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='assignments',
        ),
    ]
