# Generated by Django 5.0.1 on 2024-09-07 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentnotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentNotes',
            new_name='StudentsNotes',
        ),
    ]
