# Generated by Django 5.1.1 on 2024-10-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_studentnotes_studentsnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='fees_paid',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fees_pending',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='total_fees',
        ),
    ]
