# Generated by Django 5.1.1 on 2024-10-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='remark',
            new_name='fees_remark',
        ),
    ]
