# Generated by Django 5.1.1 on 2024-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_remark_fees_fees_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
