# Generated by Django 5.1.1 on 2024-11-06 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 12, 17, 50, 42007)),
        ),
    ]
