# Generated by Django 5.1.1 on 2024-11-06 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_fees_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 12, 20, 17, 974038)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
