# Generated by Django 5.1.1 on 2024-11-06 10:04

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_studentstasks_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='fees',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 15, 34, 26, 970908)),
        ),
    ]
