# Generated by Django 5.1.1 on 2024-11-06 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_fees_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 19, 7, 39, 831392)),
        ),
    ]
