# Generated by Django 5.1.1 on 2024-11-06 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_fees_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 11, 6, 549768)),
        ),
        migrations.AlterField(
            model_name='studentstasks',
            name='task_pdf',
            field=models.FileField(upload_to='student_taks/'),
        ),
    ]
