# Generated by Django 5.1.1 on 2024-11-06 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_fees_date_time_alter_studentstasks_task_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 15, 15, 399769)),
        ),
    ]
