# Generated by Django 5.1.1 on 2024-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='aadhaar_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
