# Generated by Django 5.1.1 on 2024-11-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
    ]
