# Generated by Django 5.0.1 on 2024-09-01 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_number', models.CharField(blank=True, max_length=50, null=True)),
                ('internship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='intern_images/')),
                ('total_fees', models.FloatField(blank=True, null=True)),
                ('fees_paid', models.FloatField(blank=True, null=True)),
                ('fees_pending', models.FloatField(blank=True, null=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='intern_notes/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='intern_videos/')),
                ('tasks', models.FileField(blank=True, null=True, upload_to='intern_tasks/')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('project_zip', models.FileField(blank=True, null=True, upload_to='intern_projects/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
