# Generated by Django 5.0.1 on 2024-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='role',
            field=models.CharField(default='Intern', max_length=20),
        ),
    ]
