# Generated by Django 5.0.1 on 2024-09-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_internprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='project_zip',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='videos',
        ),
    ]
