# Generated by Django 5.1.1 on 2024-11-03 07:32

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0004_internnotes_internproject_interntasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesIntern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fees_remark', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 11, 3, 13, 2, 22, 183973))),
                ('intern_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.internprofile')),
            ],
        ),
    ]
