# Generated by Django 5.1.1 on 2024-11-06 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0005_feesintern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesintern',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 12, 14, 3, 232891)),
        ),
    ]
