# Generated by Django 5.1.1 on 2024-11-06 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0014_alter_feesintern_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesintern',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 17, 46, 33, 850420)),
        ),
    ]
