# Generated by Django 5.1.1 on 2024-11-06 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0019_alter_feesintern_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internproject',
            name='project_description',
        ),
        migrations.AlterField(
            model_name='feesintern',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 18, 4, 524496)),
        ),
    ]
