# Generated by Django 5.1.1 on 2024-11-06 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0020_remove_internproject_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interntasks',
            name='task_description',
        ),
        migrations.AlterField(
            model_name='feesintern',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 31, 31, 350658)),
        ),
        migrations.AlterField(
            model_name='interntasks',
            name='assignment',
            field=models.FileField(upload_to='intern_assignments_tasks/'),
        ),
        migrations.AlterField(
            model_name='interntasks',
            name='task_pdf',
            field=models.FileField(upload_to='assigned_intern_taks/'),
        ),
    ]
