# Generated by Django 5.1.1 on 2024-11-06 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0021_remove_interntasks_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesintern',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 22, 19, 38, 362284)),
        ),
    ]
