# Generated by Django 5.1.1 on 2024-11-06 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0022_alter_feesintern_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesintern',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 22, 20, 56, 635658)),
        ),
    ]
